name: CÃ i Ä‘áº·t Chrome cho Windows
run-name: ChÃ o má»«ng ${{ github.actor }} ğŸš€
on:
  workflow_dispatch:
    
jobs:
  Dang_Chay:
    timeout-minutes: 360
    runs-on: windows
    name: Äang cháº¡y
    steps:
    - name: Äang cháº¡y...
      run: |
            sleep 1
            Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
            
            
            choco feature enable -n=allowGlobalConfirmation
            choco install 
      timeout-minutes: 360
    
